apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  namespace: ${K8S_NAMESPACE}
  labels:
    app: demo-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python-app
  template:
    metadata:
      labels:
        app: demo-python-app
    spec:
      imagePullSecrets:
        - name: ocir-pull
      containers:
        - name: demo-python-app
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
