apiVersion: v1
kind: Service
metadata:
  name: demo-python-app
  namespace: ${K8S_NAMESPACE}
spec:
  type: LoadBalancer
  selector:
    app: demo-python-app
  ports:
    - port: 80
      targetPort: 8080
